### PR TITLE
Fixed the wrong type for time parameterization in ompl (#55)

### PR DESCRIPTION
**Pull request by Yadunund**
Backport Fix to #54

### CODE REVIEW

**Comment by Yadunund** [comment]
@WhittemoreChou do you mind testing this branch to see if it resolves #64?

**Comment by WhittemoreChou** [comment]
> @WhittemoreChou do you mind testing this branch to see if it resolves #64?

Sorry for my late reply. It now moves! Thanks for your quick solve.
But some new warnings occur as
`WARNING:root:Cannot infer URDF from `/home/rosegm/ros_dev/egm/install/abb_irb1200_5_90_moveit_config/share/abb_irb1200_5_90_moveit_config`. -- using config/abb_bringup.urdf
WARNING:root:Cannot infer SRDF from `/home/rosegm/ros_dev/egm/install/abb_irb1200_5_90_moveit_config/share/abb_irb1200_5_90_moveit_config`. -- using config/abb_bringup.srdf`

`[move_group-1] [ERROR] [1713054841.006524743] [moveit.ros_planning.planning_pipeline]: Exception while loading planner 'chomp_interface/CHOMPPlanner': According to the loaded plugin descriptions the class chomp_interface/CHOMPPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandPlannerAvailable plugins: ompl_interface/OMPLPlanner, pilz_industrial_motion_planner/CommandPlanner`

`[move_group-1] [ERROR] [1713054841.010502628] [moveit.ros_planning_interface.moveit_cpp]: Failed to initialize planning pipeline 'chomp'.`

**Comment by Yadunund** [comment]
The warnings can be ignored.

The `chomp` error should be resolved if you run `rosdep` from the workspace. That should install [moveit_planners_chomp](https://github.com/ros/rosdistro/blob/d86c13e2c928e67eab701cb4b240abccb1df250d/humble/distribution.yaml#L4102).

**Comment by WhittemoreChou** [comment]
> The warnings can be ignored.
> 
> 
> 
> The `chomp` error should be resolved if you run `rosdep` from the workspace. That should install [moveit_planners_chomp](https://github.com/ros/rosdistro/blob/d86c13e2c928e67eab701cb4b240abccb1df250d/humble/distribution.yaml#L4102).

Thanks, I've successfully tested it on my real robot as well.

**Comment by Yadunund** [comment]
Great thanks for testing. I will merge this in.

**Pull request merged**
