### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by stephanie-eng**
Add CI to the repo + apply formatting fixes required to initially pass CI

### CODE REVIEW

**Comment by stephanie-eng** [comment]
See results of format here: https://github.com/stephanie-eng/ros2_control_abb_driver/actions/runs/2157582214

[Format](https://github.com/stephanie-eng/ros2_control_abb_driver/actions/workflows/format.yaml)

See results of build_and_test here: https://github.com/stephanie-eng/ros2_control_abb_driver/actions/runs/2157582216

[Build and Test](https://github.com/stephanie-eng/ros2_control_abb_driver/actions/workflows/build_and_test.yaml)
[Last updated 12 Apr 2022, CI run after rebasing after velocity interface was merged]

**Comment by stephanie-eng** [comment]
General test structure is based off of the ones in https://github.com/ros-planning/geometric_shapes/tree/ros2. The .clang-format is directly copied from there as well.

**Comment by AndyZe** [comment]
It would have been nice to break the formatting changes into a separate commit so it's easier for me to review

**Review by AndyZe — COMMENTED** [review]
Looks like it's working well :+1:

Can you add `pre-commit install` instructions to the documentation, then LGTM. You could copy the pre-commit blurb here:  https://moveit.ros.org/documentation/contributing/code/

**Review by AndyZe — APPROVED** [review]

**Pull request merged**
